
[buildpack]
id = "org.cloudfoundry.dep-cnb"
name = "Dep Buildpack"
version = "0.0.1"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "dep"
name = "Dep"
sha256 = "b9679cb104da5f54a3378bdafb022b48df47142a296e4e2220a61212c61cf42a"
source = "https://github.com/golang/dep/archive/v0.5.3.tar.gz"
source_sha256 = "7522588ce2d988039b15c6a7584f854223606e6ffb37c180c11b5000906a846e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dep/dep-v0.5.3-linux-x64-cflinuxfs3-b9679cb1.tgz"
version = "0.5.3"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
